# package overview
package_name: credit_risk_model

# Data files
training_data_file: train.csv
test_data_file: test.csv

# variables
#the variable we are attempting to predict (status)
target: status

pipeline_name: credit_risk_model
pipeline_save_file: credit_risk_model_output_v


# selected features 
features:     
  - seniority  
  - home       
  - time       
  - age        
  - marital    
  - records    
  - job        
  - expenses   
  - income     
  - assets     
  - debt       
  - amount     
  - price

# variable creator
categorical_vars:
  - home   
  - marital     
  - records     
  - job         

# set the train-test split
test_size: 0.3

# set the random seed
random_state: 1

# set the number of estimators
n_estimators:  100

# maximum tree depth
max_depth: 5

# log transformer constant
C: 1

# numerical variable with NA in train set
numerical_vars_with_na:
  - income 
  - assets 
  - debt 

# numerical variables to be transformed logarithimically
numerical_log_vars:
  - price 
  - amount
  - income
  - assets 
  - debt

# numerical variables to be transformed via yeojohnson
numerical_yeo_vars: 
  - seniority